Repository hellun205/princess-of-the-magic-tower, pull requests merged in 2023-09, with the labels that each got.

#26 플레이어 이동을 위한 조이스틱 구현
  Assets/Prefabs/Joystick.prefab
  Assets/Prefabs/Joystick.prefab.meta
  Assets/Scenes/SampleScene 1.unity
  Assets/Scripts/Player/PlayerMove.cs
  Assets/Scripts/UI/JoyStick.cs
  Assets/Scripts/UI/JoyStick.cs.meta
  Assets/Scripts/Util/UIMonoBehaviour.cs
  Assets/Scripts/Util/UIMonoBehaviour.cs.meta
  ProjectSettings/ProjectVersion.txt
Labels: size/L

#27 Ai
  Assets/Prefabs/PoolObjects/enemy/test4.prefab
  Assets/Prefabs/PoolObjects/enemy/test4.prefab.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scenes/TitleScene.unity
  Assets/Scenes/TitleScene.unity.meta
  Assets/Scripts/Enemy/AI.meta
  Assets/Scripts/Enemy/AI/EnemyAI.cs
  Assets/Scripts/Enemy/AI/EnemyAI.cs.meta
  Assets/Scripts/Enemy/AI/ShieldAI.cs
  Assets/Scripts/Enemy/AI/ShieldAI.cs.meta
  Assets/Scripts/Enemy/EnemyController.cs
  Assets/Scripts/Enemy/EnemyMove.cs
  Assets/Scripts/Enemy/EnemyMove.cs.meta
  Assets/Scripts/Player/PlayerMove.cs
  Assets/Scripts/Scene/SceneController.cs
  Assets/Scripts/Scene/Transition.cs
  Assets/Scripts/Scene/TransitionOption.cs
  Assets/Scripts/SceneLoad.meta
  Assets/Scripts/SceneLoad/MainMenuLoader.cs
  Assets/Scripts/SceneLoad/MainMenuLoader.cs.meta
  ProjectSettings/TagManager.asset
Labels: size/XXL

#28 bug fix with merge
  Assets/Prefabs/PoolObjects/enemy/test1.prefab
  Assets/Prefabs/PoolObjects/enemy/test2.prefab
  Assets/Prefabs/PoolObjects/enemy/test3.prefab
  Assets/Prefabs/PoolObjects/enemy/test4.prefab
  Assets/Prefabs/PoolObjects/enemy/test_dash.prefab
  Assets/Prefabs/PoolObjects/enemy/test_dash.prefab.meta
  Assets/Scenes/SampleScene 1.unity
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Enemy/AI/ShieldAI.cs
  Assets/Scripts/Enemy/EnemyController.cs
  Assets/Scripts/Map/MapManager.cs
  Assets/Scripts/Player/PlayerMove.cs
  Assets/Scripts/Pool/PoolManager.cs
  ProjectSettings/Physics2DSettings.asset
  ProjectSettings/TagManager.asset
Labels: size/XXL

#35 Add document
  Assets/Scenes/SampleScene 1.unity
  Assets/Scripts/Dialogue/AvatarCollection.cs
  Assets/Scripts/Dialogue/DStyleText.cs
  Assets/Scripts/Dialogue/DStyleText.cs.meta
  Assets/Scripts/Dialogue/DText.cs
  Assets/Scripts/Dialogue/DWait.cs
  Assets/Scripts/Dialogue/DialogueManager.cs
  Assets/Scripts/Dialogue/Script.cs
  Assets/Scripts/Dialogue/ScriptDatabase.cs
  Assets/Scripts/Dialogue/TalkerType.cs
  Assets/Scripts/Dialogue/TalkerType.cs.meta
  Assets/Scripts/Interact/InteractiveObject.cs
  Assets/Scripts/Interact/Test.cs
  Assets/Scripts/Managers/GameManager.cs
  Assets/Scripts/Managers/IDontDestoryObject.cs
  Assets/Scripts/Managers/IDontDestoryObject.cs.meta
  Assets/Scripts/Managers/IDontDestroyObject.cs
  Assets/Scripts/Managers/IDontDestroyObject.cs.meta
  Assets/Scripts/Managers/MonoBehaviourSingleton.cs
  Assets/Scripts/Managers/ObjectCollection.cs
  Assets/Scripts/Managers/ScriptableObjectCollection.cs
  Assets/Scripts/Managers/Singleton.cs
  Assets/Scripts/Map/Locker.cs
  Assets/Scripts/Map/MoveCollider.cs
  Assets/Scripts/Map/MoveCollider.cs.meta
  Assets/Scripts/Pool/PoolManager.cs
  Assets/Scripts/Pool/UsePool.cs
  Assets/Scripts/Scene/SceneController.cs
  Assets/Scripts/Scene/Transition.cs
  Assets/Scripts/Util/Binder.cs
  Assets/Scripts/Util/Utils.cs
Labels: size/XL

#37 Rotate enemy
  Assets/Prefabs/PoolObjects/enemy/test_dash.prefab
  Assets/Scenes/SampleScene 1.unity
  Assets/Scripts/Enemy/AI/ShieldAI.cs
Labels: size/L

#38 Blade ai
  Assets/Plugins/Demigiant.meta
  Assets/Plugins/Demigiant/DOTween.meta
  Assets/Plugins/Demigiant/DOTween/DOTween.XML
  Assets/Plugins/Demigiant/DOTween/DOTween.XML.meta
  Assets/Plugins/Demigiant/DOTween/DOTween.dll
  Assets/Plugins/Demigiant/DOTween/DOTween.dll.meta
  Assets/Plugins/Demigiant/DOTween/Editor.meta
  Assets/Plugins/Demigiant/DOTween/Editor/DOTweenEditor.XML
  Assets/Plugins/Demigiant/DOTween/Editor/DOTweenEditor.XML.meta
  Assets/Plugins/Demigiant/DOTween/Editor/DOTweenEditor.dll
  Assets/Plugins/Demigiant/DOTween/Editor/DOTweenEditor.dll.meta
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs.meta
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/DOTweenIcon.png
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/DOTweenIcon.png.meta
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/DOTweenMiniIcon.png
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/DOTweenMiniIcon.png.meta
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Footer.png
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Footer.png.meta
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Footer_dark.png
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Footer_dark.png.meta
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Header.jpg
  Assets/Plugins/Demigiant/DOTween/Editor/Imgs/Header.jpg.meta
  Assets/Plugins/Demigiant/DOTween/Modules.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleAudio.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleAudio.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleEPOOutline.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleEPOOutline.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModulePhysics.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModulePhysics.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModulePhysics2D.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModulePhysics2D.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleSprite.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleSprite.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUI.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUI.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUnityVersion.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUnityVersion.cs.meta
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUtils.cs
  Assets/Plugins/Demigiant/DOTween/Modules/DOTweenModuleUtils.cs.meta
  Assets/Plugins/Demigiant/DOTween/readme.txt
  Assets/Plugins/Demigiant/DOTween/readme.txt.meta
  Assets/Prefabs/PoolObjects/enemy/blade.prefab
  Assets/Prefabs/PoolObjects/enemy/blade.prefab.meta
  Assets/Prefabs/PoolObjects/enemy/shield.prefab
  Assets/Prefabs/PoolObjects/enemy/shield.prefab.meta
  Assets/Resources.meta
  Assets/Resources/DOTweenSettings.asset
  Assets/Resources/DOTweenSettings.asset.meta
  Assets/Scenes/SampleScene 1.unity
  Assets/Scripts/Enemy/AI/BladeAI.cs
  Assets/Scripts/Enemy/AI/BladeAI.cs.meta
  Assets/Scripts/Enemy/AI/ShieldAI.cs
  Assets/Sprites/Enemy.meta
  Assets/Sprites/Enemy/Blade.meta
  Assets/Sprites/Enemy/Blade/8a4eaf4bab824e73549017d15bbc59d0(1).png
  Assets/Sprites/Enemy/Blade/8a4eaf4bab824e73549017d15bbc59d0(1).png.meta
  Assets/Sprites/Enemy/Blade/pngwing.com.png
  Assets/Sprites/Enemy/Blade/pngwing.com.png.meta
Labels: size/XXL

#45 Light system
  Assets/Prefabs/Awwow.prefab
  Assets/Prefabs/Dash.prefab
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/Player.prefab.meta
  Assets/Prefabs/PoolObjects/enemy/blade.prefab
  Assets/Prefabs/PoolObjects/enemy/shield.prefab
  Assets/Prefabs/PoolObjects/enemy/test1.prefab
  Assets/Prefabs/PoolObjects/enemy/test2.prefab
  Assets/Prefabs/PoolObjects/enemy/test3.prefab
  Assets/Prefabs/PoolObjects/enemy/test_additionaldash.prefab
  Assets/Prefabs/Stage.meta
  Assets/Prefabs/Stage/Stage1.meta
  Assets/Prefabs/Stage/Stage1/DaySwitch.prefab
  Assets/Prefabs/Stage/Stage1/DaySwitch.prefab.meta
  Assets/Prefabs/Stage/Stage1/NightSwitch.prefab
  Assets/Prefabs/Stage/Stage1/NightSwitch.prefab.meta
  Assets/Resources/Player.prefab
  Assets/Scenes/SampleScene 1.meta
  Assets/Scenes/SampleScene 1.unity
  Assets/Scenes/SampleScene 1/LightingData.asset
  Assets/Scenes/SampleScene 1/LightingData.asset.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scenes/TitleScene.unity
  Assets/Scripts/Enemy/AI/ShieldAI.cs
  Assets/Scripts/Interact/InteractCondition.cs
  Assets/Scripts/Interact/InteractCondition.cs.meta
  Assets/Scripts/Interact/InteractType.cs
  Assets/Scripts/Interact/InteractType.cs.meta
  Assets/Scripts/Interact/InteractiveObject.cs
  Assets/Scripts/Interact/Object.meta
  Assets/Scripts/Interact/Object/LightSwitch.cs
  Assets/Scripts/Interact/Object/LightSwitch.cs.meta
  Assets/Scripts/Interact/Object/Test.cs
  Assets/Scripts/Interact/Object/Test.cs.meta
  Assets/Scripts/Interact/Test.cs.meta
  Assets/Scripts/Player/PlayerLight.cs
  Assets/Scripts/Player/PlayerLight.cs.meta
  Assets/Scripts/Player/PlayerManager.cs
  Assets/Scripts/Player/PlayerMove.cs
  Assets/URP.meta
  Assets/URP/LightSettings.meta
  Assets/URP/LightSettings/Stage_1.lighting
  Assets/URP/LightSettings/Stage_1.lighting.meta
  Assets/URP/New 2D Renderer Data.asset
  Assets/URP/New 2D Renderer Data.asset.meta
  Assets/URP/New Universal Render Pipeline Asset.asset
  Assets/URP/New Universal Render Pipeline Asset.asset.meta
  Assets/URP/New Universal Render Pipeline Asset_Renderer.asset
  Assets/URP/New Universal Render Pipeline Asset_Renderer.asset.meta
  Assets/URP/UniversalRenderPipelineGlobalSettings.asset
  Assets/URP/UniversalRenderPipelineGlobalSettings.asset.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/GraphicsSettings.asset
  ProjectSettings/QualitySettings.asset
  ProjectSettings/ShaderGraphSettings.asset
  ProjectSettings/URPProjectSettings.asset
Labels: size/XXL

#48 Update README.md
  README.md
Labels: size/XS

#55 가시 함정
  Assets/Animation/Trap/Sample.meta
  Assets/Animation/Trap/Sample/Thorn.meta
  Assets/Animation/Trap/Sample/Thorn/OnActivate.anim
  Assets/Animation/Trap/Sample/Thorn/OnActivate.anim.meta
  Assets/Animation/Trap/Sample/Thorn/OnDeactivate.anim
  Assets/Animation/Trap/Sample/Thorn/OnDeactivate.anim.meta
  Assets/Animation/Trap/Sample/Thorn/thorn_trap.controller
  Assets/Animation/Trap/Sample/Thorn/thorn_trap.controller.meta
  Assets/Editor/MenuUtility.cs
  Assets/Resources/Custom/Trap.meta
  Assets/Resources/Custom/Trap/thorn.prefab
  Assets/Resources/Custom/Trap/thorn.prefab.meta
  Assets/Samples/함정.png.meta
  Assets/Scenes/Stage/TestPlace.unity
  Assets/Scenes/Stage/TestPlace.unity.meta
  Assets/Scripts/Trap/ThornTrap.cs
  Assets/Scripts/Trap/ThornTrap.cs.meta
  Assets/Scripts/Trap/Trap.cs
  Assets/Scripts/Trap/Trap.cs.meta
  Assets/Scripts/Trap/TrapCondition.cs
  Assets/Scripts/Trap/TrapCondition.cs.meta
  Assets/Scripts/Util/Detector.cs
  Assets/Scripts/Util/Detector.cs.meta
  Assets/Scripts/Util/Utils.cs
Labels: size/XXL

#63 대쉬 버튼
  Assets/Resources/GameManager.prefab
  Assets/Resources/Player.prefab
  Assets/Scripts/Player/PlayerMove.cs
  Assets/Scripts/Player/PlayerSkill.cs
  Assets/Scripts/UI/CooledTouch.cs
  Assets/Scripts/UI/CooledTouch.cs.meta
  Assets/Scripts/UI/Touch.cs
  Assets/Scripts/Util/Timer.cs
  Assets/Sprites/UI/icon_dash.png
  Assets/Sprites/UI/icon_dash.png.meta
  Assets/Sprites/UI/icon_menu.png
  Assets/Sprites/UI/icon_menu.png.meta
Labels: size/XL

#68 스테이지 1 보강 / 버그 수정
  Assets/Animation/Enemy/FrogEnemy_iDLE.anim
  Assets/Animation/Enemy/frog.controller
  Assets/Prefabs/PoolObjects/Bullet/Bullet_obj.prefab
  Assets/Scenes/Stage/test.unity
  Assets/Scripts/Enemy/AI/FrogAI.cs
  Assets/Scripts/Player/PlayerManager.cs
  Assets/Scripts/Player/PlayerSkill.cs
  Assets/Scripts/Player/UI/DashCountBar.cs
Labels: size/XXL

#69 Line path editor
  Assets/Editor/LinePathCreatorEditor.cs
  Assets/Editor/LinePathCreatorEditor.cs.meta
  Assets/Scenes/Stage/test.unity
  Assets/Scripts/LinePath/LineFollower.cs
  Assets/Scripts/LinePath/LinePathCreator.cs
Labels: size/L

#70 Timer Ease in / out feature, editor ui
  Assets/Editor/TimerEditor.cs
  Assets/Editor/TimerEditor.cs.meta
  Assets/Resources/Custom/Trap/thorn_block.prefab
  Assets/Scenes/Stage/test.unity
  Assets/Scripts/LinePath/LineFollower.cs
  Assets/Scripts/Player/PlayerSkill.cs
  Assets/Scripts/Trap/Object/ThornBlock.cs
  Assets/Scripts/Trap/Trap.cs
  Assets/Scripts/UI/CooledTouch.cs
  Assets/Scripts/Util/MathUtility.cs
  Assets/Scripts/Util/MathUtility.cs.meta
  Assets/Scripts/Util/Timer.cs
  Assets/Scripts/Util/TimerType.cs
  Assets/Scripts/Util/TimerType.cs.meta
  Assets/Scripts/Util/Utils.cs
Labels: size/L

#71 Room Editor
  Assets/Animation/SceneTransition/Transition.controller
  Assets/Data.meta
  Assets/Data/RoomResource.meta
  Assets/Data/RoomResource/Stage1.meta
  Assets/Data/RoomResource/Stage1/stage_1_1_night_1.asset
  Assets/Data/RoomResource/Stage1/stage_1_1_night_1.asset.meta
  Assets/Data/RoomResource/Stage1/stage_1_1_night_2.asset
  Assets/Data/RoomResource/Stage1/stage_1_1_night_2.asset.meta
  Assets/Data/RoomResource/Stage1/stage_1_1_night_3.asset
  Assets/Data/RoomResource/Stage1/stage_1_1_night_3.asset.meta
  Assets/Data/RoomResource/Stage1/stage_1_1_night_4.asset
  Assets/Data/RoomResource/Stage1/stage_1_1_night_4.asset.meta
  Assets/Data/RoomResource/Stage1/stage_1_1_normal_1.asset
  Assets/Data/RoomResource/Stage1/stage_1_1_normal_1.asset.meta
  Assets/Data/RoomResource/Stage1/stage_1_1_normal_2.asset
  Assets/Data/RoomResource/Stage1/stage_1_1_normal_2.asset.meta
  Assets/Data/RoomResource/Stage1/stage_1_1_normal_3.asset
  Assets/Data/RoomResource/Stage1/stage_1_1_normal_3.asset.meta
  Assets/Data/RoomResource/Stage1/stage_1_1_normal_4.asset
  Assets/Data/RoomResource/Stage1/stage_1_1_normal_4.asset.meta
  Assets/Editor/DoorEditor.cs
  Assets/Editor/DoorEditor.cs.meta
  Assets/Editor/RoomEditor.cs
  Assets/Editor/RoomEditor.cs.meta
  Assets/Editor/StageContollerEditor.cs
  Assets/Editor/StageContollerEditor.cs.meta
  Assets/Resources/Custom/Room/Door/bottom.prefab
  Assets/Resources/Custom/Room/Door/left.prefab
  Assets/Resources/Custom/Room/Door/right.prefab
  Assets/Resources/Custom/Room/Door/top.prefab
  Assets/Resources/Custom/Room/room.prefab
  Assets/Resources/GameManager.prefab
  Assets/Scenes/Stage/test.unity
  Assets/Scripts/Enemy/AI/FrogAI.cs
  Assets/Scripts/LinePath/LineFollower.cs
  Assets/Scripts/Map/Door/Door.cs
  Assets/Scripts/Map/Door/DoorType.cs
  Assets/Scripts/Map/Door/DoorType.cs.meta
  Assets/Scripts/Map/Door/DoorUtility.cs
  Assets/Scripts/Map/Door/DoorUtility.cs.meta
  Assets/Scripts/Map/Door/FixedDoor.cs
  Assets/Scripts/Map/Door/FixedDoor.cs.meta
  Assets/Scripts/Map/Door/KillEnemyDoor.cs
  Assets/Scripts/Map/Door/KillEnemyDoor.cs.meta
  Assets/Scripts/Map/IRoomEnterEventHandler.cs
  Assets/Scripts/Map/IRoomEnterEventHandler.cs.meta
  Assets/Scripts/Map/IRoomExitEventHandler.cs
  Assets/Scripts/Map/IRoomExitEventHandler.cs.meta
  Assets/Scripts/Map/Link.cs
  Assets/Scripts/Map/Link.cs.meta
  Assets/Scripts/Map/MapManager.cs
  Assets/Scripts/Map/Room.cs
  Assets/Scripts/Map/RoomResource.cs
  Assets/Scripts/Map/RoomResource.cs.meta
  Assets/Scripts/Player/UI/DashCountBar.cs
  Assets/Scripts/Pool/PoolSummoner.cs
  Assets/Scripts/Trap/Trap.cs
  Assets/Scripts/Util/Timer.cs
Labels: size/XXL
